services:
  postgres:
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - maven_cache:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "4200:4200"
    command: ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"

volumes:
  maven_cache:
  node_modules:
